### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by gaurav-singh1990** [dtreelabs/specterr#5]
Currently we are creating default database in sqlite and creating tables inside it. We have to make it configurable so that if user wants she can create database in their own databases by providing the database connection details.
We can think of implementation in following ways:-
i) Check for ```spectr.yml``` in ```Rails.root/config```.
ii) If found ```spectr.yml``` in ```Rails.root/config``` then read database details from the file, create database connection from the details and initialize database if not already initialized.
iii) If file is not present then create ```sqlite``` database inside ```Rails.root```.
PR: #9

**Comment by akshaymohite** [comment]
Closed by #9
